steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/sharetext-repo/sharetext',
      '.'
    ]

  # Push image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-south1-docker.pkg.dev/$PROJECT_ID/sharetext-repo/sharetext'
    ]

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run','deploy','my-service',
      '--image','asia-south1-docker.pkg.dev/$PROJECT_ID/sharetext-repo/sharetext',
      '--region','asia-south1',
      '--platform','managed',
      '--allow-unauthenticated',
      '--set-env-vars=DB_URL=jdbc:mysql://[YOUR_PROD_DB_IP]:3306/sharetext,DB_USERNAME=[ID],DB_PASSWORD=[PASS]'
    ]

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/sharetext-repo/sharetext'